package com.basics.threads;

class ResultClass extends Thread{
    @Override
    public void run(){
        System.out.println("result Generated by " + Thread.currentThread().getName());
    }

    public static void main(String[] args) {
        ResultClass t1= new ResultClass();
        t1.run();
        t1.start();
    }
}
/*
///';points to remeber;
/star()=multiple -multitasking-concurreny
//run()=normal exceution
///star()=internally calls run
 /// threads can not be stared twice
 */